const types = {
    BACKEND_REQUEST_START:"BACKEND_REQUEST_START",
    
    GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
    GET_ALL_DATA_FAIL: 'GET_ALL_DATA_FAIL',

    POST_NEW_DATA_SUCCESS: 'POST_NEW_DATA_SUCCESS',
    POST_NEW_DATA_FAIL: 'POST_NEW_DATA_FAIL',

  };
  
  export default types;
  